CREATE TABLE QNABBS(
	POST_NUMBER NUMBER(10) PRIMARY KEY,
	EMAIL VARCHAR2(50),
	TITLE VARCHAR2(200) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	STEP NUMBER(5) NOT NULL,
	REF NUMBER(5) NOT NULL,
	DEL NUMBER(5) NOT NULL,
	WDATE DATE NOT NULL,
	CONSTRAINT FK_EMAIL FOREIGN KEY(EMAIL)
    REFERENCES MEMBER(EMAIL)
);

CREATE TABLE MAINBBS(
	POST_NUMBER NUMBER(10) PRIMARY KEY,
	EMAIL VARCHAR2(50),
	TITLE VARCHAR2(200) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	LOCATION VARCHAR2(50) NOT NULL,
	AUTH_CHECK NUMBER(5) NOT NULL,
	IMGNAME VARCHAR2(50) NOT NULL,
	ORIGINFILENAME VARCHAR2(50) NOT NULL,
	CONSTRAINT FK_MAIN_EMAIL FOREIGN KEY(EMAIL)
    REFERENCES MEMBER(EMAIL)
	
);

ALTER TABLE MAINBBS
ADD WDATE DATE;

CREATE TABLE MAINLIKE(
	LIKE_NUMBER NUMBER(5) PRIMARY KEY,
	EMAIL VARCHAR2(50),
	MAIN_POST_NUMBER NUMBER(10),
	LIKE_COUNT NUMBER(10) NOT NULL,
	CONSTRAINT FK_LIKE_EMAIL FOREIGN KEY(EMAIL)
    REFERENCES MEMBER(EMAIL),
    CONSTRAINT FK_MAIN_POST2 FOREIGN KEY(MAIN_POST_NUMBER)
    REFERENCES MAINBBS(POST_NUMBER)
);
	

CREATE TABLE MAINCOMMENT(
	POST_NUMBER NUMBER(10) PRIMARY KEY,
	EMAIL VARCHAR2(50),
	MAIN_POST_NUMBER NUMBER(10),
	CONTENT VARCHAR2(4000) NOT NULL,
	STEP NUMBER(5) NOT NULL,
	REF NUMBER(5) NOT NULL,
	DEL NUMBER(5) NOT NULL,
	WDATE DATE NOT NULL,
	CONSTRAINT FK_COMMENT_EMAIL FOREIGN KEY(EMAIL)
    REFERENCES MEMBER(EMAIL),
    CONSTRAINT FK_MAIN_POST FOREIGN KEY(MAIN_POST_NUMBER)
    REFERENCES MAINBBS(POST_NUMBER)
);

CREATE TABLE SANBBS(
	POST_NUMBER NUMBER(5) PRIMARY KEY,
	NAME VARCHAR2(50) NOT NULL,
	HEIGHT NUMBER(10) NOT NULL,
	COURSE VARCHAR2(4000) NOT NULL,
	INFO VARCHAR2(4000) NOT NULL,
	TRANSPORT VARCHAR2(2000) NOT NULL,
	LOCATION VARCHAR2(50) NOT NULL,
	IMGNAME VARCHAR2(50),
	ORIGINFILENAME VARCHAR2(50)
);

CREATE SEQUENCE SEQ_QNABBS
START WITH 1
INCREMENT BY 1

CREATE SEQUENCE SEQ_MAINBBS
START WITH 1
INCREMENT BY 1

CREATE SEQUENCE SEQ_COMMENT
START WITH 1
INCREMENT BY 1

CREATE SEQUENCE SEQ_LIKE
START WITH 1
INCREMENT BY 1